#!/usr/bin/env bash
# init-template.sh — rename the `appname` placeholder in a copied template directory
#
# Usage:
#   scripts/init-template.sh <target-dir> <project-name>
#
# Example:
#   cp -R node-example/templates/localhost ./my-app
#   bash node-example/scripts/init-template.sh ./my-app my-app
#
# What it does:
#   1. Validates <project-name> (kebab-case, starts with letter)
#   2. Verifies the target still has the `appname` placeholder (refuses to run twice)
#   3. Replaces `appname`  -> <project-name>  and  `Appname` -> <PascalCase>
#      in every text file under <target-dir> (excluding node_modules, .git, dist).

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <target-dir> <project-name>" >&2
  exit 64
fi

TARGET_DIR="$1"
NAME="$2"

if [[ ! -d "$TARGET_DIR" ]]; then
  echo "error: target directory does not exist: $TARGET_DIR" >&2
  exit 66
fi

if [[ ! "$NAME" =~ ^[a-z][a-z0-9-]*$ ]]; then
  echo "error: project name must be lowercase kebab-case (e.g. my-app), got: $NAME" >&2
  exit 65
fi

if [[ "$NAME" == "appname" ]]; then
  echo "error: '$NAME' is the placeholder itself" >&2
  exit 65
fi

if ! grep -q '"@appname/source"' "$TARGET_DIR/package.json" 2>/dev/null; then
  echo "error: $TARGET_DIR/package.json does not contain the @appname/ placeholder." >&2
  echo "       Either this is the wrong directory, or it was already renamed." >&2
  exit 70
fi

# PascalCase: "my-app" -> "MyApp", "foo" -> "Foo"
pascal_case() {
  local input="$1"
  local result=""
  local IFS='-'
  for segment in $input; do
    if [[ -n "$segment" ]]; then
      result+="$(tr '[:lower:]' '[:upper:]' <<< "${segment:0:1}")${segment:1}"
    fi
  done
  echo "$result"
}

PASCAL_NAME=$(pascal_case "$NAME")

echo "Renaming placeholder in: $TARGET_DIR"
echo "  appname -> $NAME"
echo "  Appname -> $PASCAL_NAME"

# Find every text file (heuristic: file -b reports something with 'text' or 'JSON' or 'empty')
# Exclude vendored / generated dirs.
cd "$TARGET_DIR"
find . \
  \( -path ./node_modules -o -path ./.git -o -path ./dist -o -path ./tmp -o -path './.nx' \) -prune \
  -o -type f -print0 |
  while IFS= read -r -d '' file; do
    # Skip binaries
    if file -b --mime-encoding "$file" | grep -q 'binary'; then
      continue
    fi
    # Skip the lockfile — it'll be regenerated by pnpm install
    case "$file" in
      ./pnpm-lock.yaml|./package-lock.json|./yarn.lock) continue ;;
    esac
    perl -i -pe "s/\\bappname\\b/$NAME/g; s/\\bAppname\\b/$PASCAL_NAME/g" "$file"
  done

echo "Done. Next steps:"
echo "  1. cd $TARGET_DIR && pnpm install"
echo "  2. pnpm supabase start            # boots Postgres / Auth / Realtime / Storage / Studio locally"
echo "  3. pnpm supabase status           # values to paste into .env"
echo "  4. cp .env.example .env && \$EDITOR .env"
echo "  5. pnpm nx run api:migrate-run"
echo "  6. pnpm nx serve api              # backend on http://localhost:3000"
echo "  7. pnpm nx serve ui               # frontend on http://localhost:4200 (other terminal)"
